name = "ImageModifierProject"
uuid = "29348444-9bd8-4545-be9b-6143104b5ff9"
authors = ["Antipurity <45312367+Antipurity@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
